name: delete-comments
description: Delete uninformative SonarCloud PR comments
runs:
  using: composite
  steps:
  - name: Check cache key1
    run: echo ${{ github.action_path }}
    shell: bash

  - name: Check cache key2
    run: echo ${{ format('{0}/{1}', github.action_path, 'package-lock.json') }}
    shell: bash

  - name: Check cache key3
    run: echo ${{ hashFiles(format('{0}/{1}', github.action_path, 'package-lock.json')) }}
    shell: bash

  - name: Cache node_modules step
    id: cache
    uses: actions/cache@v2
    with:
      path: ${{ github.action_path }}/node_modules
      key: actions-delete-comments-${{ hashFiles(format('{0}/{1}', github.action_path, 'package-lock.json')) }}

  - name: Install dependencies step2
    run: ls -alR ${{ github.action_path }}
    shell: bash

  - name: Install dependencies step
    if: ${{ steps.cache.outputs.cache-hit != 'true' }}
    run: cd ${{ github.action_path }} && npm ci --ignore-scripts
    shell: bash

  - name: Run step
    run: node ${{ github.action_path }}/index.js
    shell: bash
