name: delete-comments
description: Delete uninformative SonarCloud PR comments
runs:
  using: composite
  steps:
  - name: Cache node_modules step
    id: cache
    uses: actions/cache@v2
    with:
      path: delete-comments/node_modules
      key: actions-delete-comments-${{ hashFiles('delete-comments/package-lock.json') }}

  - name: Install dependencies step1
    run: pwd
    shell: bash

  - name: Install dependencies step2
    run: ls -alR ..
    shell: bash

  - name: Install dependencies step
    if: ${{ steps.cache.outputs.cache-hit != 'true' }}
    run: cd delete-comments && npm ci --ignore-scripts
    shell: bash

  - name: Run step
    run: node delete-comments/index.js
    shell: bash
